GET http://localhost:3333/products

###

POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "book 2",
  "price": 20,
  "quantity": 5
}

###

GET http://localhost:3333/products/34f3f482-8441-4682-b1e4-fa02286984c6

###

PUT http://localhost:3333/products/34f3f482-8441-4682-b1e4-fa02286984c6
Content-Type: application/json

{
  "name": "book 23",
  "price": 2033,
  "quantity": 599
}

###

DELETE http://localhost:3333/products/fafc16f2-acf6-44f5-8466-1ec2665e1f5c
Content-Type: application/json

###################################################

GET http://localhost:3333/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTQ4ODI3NjUsImV4cCI6MTYxNDk2OTE2NSwic3ViIjoiNWM0ZGE1YjEtZjhlYi00YmE0LWExODMtZTk1ZWQzYTkxZGUwIn0.IpXUeiaaCrDK5i7duc700_V-PHD0OCoBcP4ifxByHcY

###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Tiago6",
  "email": "tetigo6@gmail.com",
  "password": "12345"
}

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "tetigo6@gmail.com",
  "password": "12345"
}

###

GET http://localhost:3333/sessions

###

