GET http://localhost:3333/products

###

POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "book 125",
  "price": 2015,
  "quantity": 155
}

###

GET http://localhost:3333/products/ea115c6b-23e4-461a-a1e0-9366c9ed8602

###

PUT http://localhost:3333/products/ea115c6b-23e4-461a-a1e0-9366c9ed8602
Content-Type: application/json

{
  "name": "book 23",
  "price": 2033,
  "quantity": 599
}

###

DELETE http://localhost:3333/products/894970ec-29f2-4de6-9754-67d8d1fc596b
Content-Type: application/json

###################################################

GET http://localhost:3333/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM
###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Tiago8",
  "email": "tetigo8@gmail.com",
  "password": "12345678"
}

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "tetigo8@gmail.com",
  "password": "12345678"
}

###


PATCH http://localhost:3333/users/avatar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTYxMTE5MjcsImV4cCI6MTYxNjE5ODMyNywic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.zoUHKpoZxPvJVsLPFCazxZEH8HFhr48-rhDrsMbZGuM
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="simpson1.png"
Content-Type: image/jpeg

< ./simpson1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST http://localhost:3333/password/forgot
Content-Type: application/json

{
  "email": "tetigo4@gmail.com"
}

###

POST http://localhost:3333/password/reset
Content-Type: application/json

{
  "token": "fd931619-d024-43d4-86e2-7dd794c6578c",
  "password": "123123",
  "password_confirmation": "123123"
}

###

GET http://localhost:3333/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM

###

PUT http://localhost:3333/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM
Content-Type: application/json

{
  "name": "Tigo2",
  "email": "tetigo8@gmail.com",
  "password": "abc",
  "password_confirmation": "abc",
  # "old_password": "12345678"
}

###
#Nesse padrao sem query params retorna 15 por pagina default
GET http://localhost:3333/customers/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM

###

GET http://localhost:3333/customers/?page=1&per_page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM

###

GET http://localhost:3333/customers/dbbffc22-1c49-4e49-beb8-89e026d90d93
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM

###

POST http://localhost:3333/customers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU1ODgwMDEsImV4cCI6MTYxNTY3NDQwMSwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.QI_pLZdDqkiJv2ACGC4SsMXvKOve2V47z5KCYA9j_5Q
Content-Type: application/json

{
  "name": "Tetigo665",
  "email": "tetigo665@gmail.com"
}

####

PUT http://localhost:3333/customers/4a693ab7-d49a-4f1b-a482-004bb0b30497
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU1ODgwMDEsImV4cCI6MTYxNTY3NDQwMSwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.QI_pLZdDqkiJv2ACGC4SsMXvKOve2V47z5KCYA9j_5Q
Content-Type: application/json

{
  "name": "Tetigo778",
  "email": "tetigo778@gmail.com"
}

###

DELETE http://localhost:3333/customers/e4c87f5c-103d-4e78-a6df-ccb9cd0a2590
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU1ODgwMDEsImV4cCI6MTYxNTY3NDQwMSwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.QI_pLZdDqkiJv2ACGC4SsMXvKOve2V47z5KCYA9j_5Q

###

POST http://localhost:3333/orders/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM
Content-Type: application/json

{
  "customer_id": "dbbffc22-1c49-4e49-beb8-89e026d90d93",
  "products": [
    {
      "product_id": "b222680d-9abc-4ff1-9f2c-b4cc080a3571",
      "quantity": 3
    },
    {
      "product_id": "ea115c6b-23e4-461a-a1e0-9366c9ed8602",
      "quantity": 20 
    }
  ]
}


###

POST http://localhost:3333/orders/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM
Content-Type: application/json

{
  "customer_id": "dbbffc22-1c49-4e49-beb8-89e026d90d93",
  "products": [
    {
      "product_id": "db3acf71-c2a7-4fe1-9d0b-ee8236d2e100",
      "quantity": 5
    }
  ]
}
###

GET http://localhost:3333/orders/a68bebe6-c48c-4c2f-903e-4ed4e7d905d7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTU5MzY3NDAsImV4cCI6MTYxNjAyMzE0MCwic3ViIjoiZDdiODI2ZGQtMzJlNC00M2NmLTlkZjYtZDJkZTljMWEzZGQ5In0.RdlHSjxCDHzqQjzQ2Cr1edmSg3fZSfDm-YlQLpmTUGM

###

