GET http://localhost:3333/products

###

POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "book 12",
  "price": 201,
  "quantity": 15
}

###

GET http://localhost:3333/products/6a6b8f09-61ea-4616-9a16-8523dc57cc54

###

PUT http://localhost:3333/products/6a6b8f09-61ea-4616-9a16-8523dc57cc54
Content-Type: application/json

{
  "name": "book 23",
  "price": 2033,
  "quantity": 599
}

###

DELETE http://localhost:3333/products/fafc16f2-acf6-44f5-8466-1ec2665e1f5c
Content-Type: application/json

###################################################

GET http://localhost:3333/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTQ4ODI3NjUsImV4cCI6MTYxNDk2OTE2NSwic3ViIjoiNWM0ZGE1YjEtZjhlYi00YmE0LWExODMtZTk1ZWQzYTkxZGUwIn0.IpXUeiaaCrDK5i7duc700_V-PHD0OCoBcP4ifxByHcY

###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Tiago6",
  "email": "tetigo6@gmail.com",
  "password": "12345"
}

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "tetigo6@gmail.com",
  "password": "12345"
}

###

GET http://localhost:3333/sessions

###

PATCH http://localhost:3333/users/avatar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRhdGkiOiJwYXRhdGEiLCJpYXQiOjE2MTQ5NTY5MTQsImV4cCI6MTYxNTA0MzMxNCwic3ViIjoiNjY0YjYxZDctNDBhYi00MjIzLWE1MjItYzRhZjA0MGUxY2RlIn0.ANV3KBaXuv2cyAIOnmnKN_JWyw05HrNqEn_F8MGsZpI
Content-Type: multipart/form-data; boundary=------WebKitFormBoundary7MA4YWxkTrZu0gW
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="simpson1.jpg"
Content-Type: image/jpeg

< ./simpson1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###





